DROP TABLE IF EXISTS vegetables CASCADE;

CREATE TABLE vegetables (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  name TEXT NOT NULL UNIQUE,
  genus TEXT NOT NULL, 
  family TEXT NOT NULL,
  order TEXT NOT NULL,
  nutritions JSON NOT NULL,
)